name: Bug Report
description: If you've already asked for help with a problem and confirmed something is broken with the plugin itself, create a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees: olimorris

body:
    - type: markdown
      attributes:
        value: |
          Thanks for taking the time to fill out this bug report! This form may seem onerous but it makes a resolution much quicker for you and I.
    - type: markdown
      attributes:
        value: |
          ## Test with a minimal.lua file
          Firstly, test and run Neovim with the minimal config below. Be sure to add your own config, saving to a `minimal.lua` file and adding any additional plugins you may need:

          ```lua
          local root = vim.fn.fnamemodify("./.repro", ":p")

          -- set stdpaths to use .repro
          for _, name in ipairs({ "config", "data", "state", "cache" }) do
            vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
          end

          -- bootstrap lazy
          local lazypath = root .. "/plugins/lazy.nvim"
          if not vim.loop.fs_stat(lazypath) then
            vim.fn.system({
              "git",
              "clone",
              "--filter=blob:none",
              "--single-branch",
              "https://github.com/folke/lazy.nvim.git",
              lazypath,
            })
          end
          vim.opt.runtimepath:prepend(lazypath)

          -- install plugins
          local plugins = {
            {
              "nvim-treesitter/nvim-treesitter",
              build = ":TSUpdate",
              config = function()
                require("nvim-treesitter.configs").setup({
                  ensure_installed = "ruby",
                })
              end,
            },
            {
              "nvim-neotest/neotest",
              lazy = true,
              dependencies = {
                "olimorris/neotest-rspec",
              },
              config = function()
                require("neotest").setup({
                  adapters = {
                    require("neotest-rspec"),
                  },
                })
              end,
            },
          }

          require("lazy").setup(plugins, {
            root = root .. "/plugins",
          })
          ```

          Once you"ve updated for your config, run Neovim with this command:
          ```sh
          nvim --clean -u minimal.lua
          ```
          > **Note:** You may need to do this a couple of times for Treesitter to fully download and sync

    - type: textarea
      id: neotest-rspec-config
      attributes:
        label: Your neotest-rspec config
        description: Please paste your specific neotest-rspec config
        placeholder: |
          ```lua
          -- Your config here
          ```
      validations:
        required: true

    - type: textarea
      id: errors
      attributes:
        label: Error messages
        description: Please paste any error messages you receive
        placeholder: |
          ```lua
          -- Error messages here
          ```
      validations:
        required: false

    - type: textarea
      id: rspec-test
      attributes:
        label: RSpec test
        description: Please share the RSpec test you're testing (optional)
        placeholder: |
          ```ruby
          -- RSpec test here
          ```

    - type: textarea
      id: bug
      attributes:
        label: Describe the bug
        description: Please describe the bug and include any screenshots
        placeholder: |
          ### What I expect to happen
          [Your text here]

          ### What actually happens
          [Your text here]
      validations:
        required: true

    - type: textarea
      id: reproduce
      attributes:
        label: Reproduce the bug
        description: Please include the steps to reproduce the bug
        placeholder: |
          Steps to reproduce:
          1.
          2.
          3.
      validations:
        required: false

    - type: checkboxes
      id: final-checks
      attributes:
        label: Final checks
        description: |
          Before you submit, please make sure you have completed the following steps:
        options:
          - label: I have made sure this issue exists in the latest version of the plugin
            required: true
          - label: I have tested with the `minimal.lua` config file above and still get the issue
            required: true
          - label: I have confirmed that Treesitter is working correctly by running `:checkhealth treesitter`
            required: true
          - label: I have made sure this is not a duplicate issue
            required: true
